### ISSUE TITLE
QTMConnectLiveLink_5.1 does not seem to be working with Unreal Engine 5.1.1

### ISSUE THREAD

**Issue by ghost** [qualisys/QTM-Connect-For-Unreal#60]
When enabling the plugin (have tried both 1.3 and 1.4) in Unreal Engine 5.1.1 along with the Live Link plugin and restarting Unreal I get an error message saying:

The following modules are missing or built with a different engine version:
QTMConnectLiveLink
QTMConnectLiveLinkEditor
Engine modules cannot be compiled at runtime. Please build through your IDE.

Is the plugin not yet compatible with 5.1.1? If that's the case, when can we expect an update?
UE version 5.1.0 does not seem to be available in the Epic Games Launcher anymore which puts me in a dead end.

**Comment by ulvs** [comment]
Hi,

The plugin should be compatible with 5.1, we are running that. But you could run it fram the source and let UE compile it in your project if you have problems.
If this does not help please reach out to support@qualisys.com and we can assist.
